/// @description Insert description here
// You can write your code in this editor

draw_set_font(fnt_pixel);
draw_set_halign(fa_left);
draw_set_valign(fa_top);

var string_val_upk,string_val_dwk,string_val_lk,string_val_rk,string_val_jk,string_val_ak,string_val_dk,string_val_ik;

//player_input_keyb(upk,string_val_upk);

//player_input_keyb(upk,string_val_upk);

switch(upk)
    {
        case vk_up: string_val_upk = "up key";break;
        case vk_down: string_val_upk = "down key";break;
        case vk_left: string_val_upk = "left key";break;
        case vk_right: string_val_upk = "right key";break;
        case vk_lcontrol: string_val_upk = "l ctrl";break;
        case vk_shift: string_val_upk = "shift"; break;
        case vk_lalt: string_val_upk = "l alt";break;
        case vk_tab: string_val_upk = "tab";break;
        case 20: string_val_upk = "caps lock";break;
        case 192: string_val_upk = "`";break;
        case 8:   string_val_upk = "backspace";break;
        case 189: string_val_upk = "-";break;
        case 187: string_val_upk = "=";break;
        case 219: string_val_upk = "[";break;
        case 221: string_val_upk = "]";break;
        case 220: string_val_upk = "|";break;
        case 165: string_val_upk = "r alt";break;
        case 163: string_val_upk = "r ctrl";break;
        case 96:  string_val_upk = "num 0";break;
        case 110: string_val_upk = "num .";break;
        case 97:  string_val_upk = "num 1";break;
        case 98:  string_val_upk = "num 2";break;
        case 99:  string_val_upk = "num 3";break;
        case 100: string_val_upk = "num 4";break;
        case 101: string_val_upk = "num 5";break;
        case 102: string_val_upk = "num 6";break;
        case 103: string_val_upk = "num 7";break;
        case 104: string_val_upk = "num 8";break;
        case 105: string_val_upk = "num 9";break;
        case 107: string_val_upk = "num +";break;
        case 144: string_val_upk = "num lock";break;
        case 111: string_val_upk = "num /";break;
        case 106: string_val_upk = "num *";break;
        case 109: string_val_upk = "num -";break;
        case 145: string_val_upk = "scroll lock";break;
        case 186: string_val_upk = ";";break;
        case 222: string_val_upk = "'";break;
        case 188: string_val_upk = ",";break;
        case 190: string_val_upk = ".";break;
        case 191: string_val_upk = "/";break;
        case 32:  string_val_upk = "space";break;
        default:  string_val_upk = chr(upk);break;
    }
switch(dwk)
    {
        case vk_up: string_val_dwk = "up key";break;
        case vk_down: string_val_dwk = "down key";break;
        case vk_left: string_val_dwk = "left key";break;
        case vk_right: string_val_dwk = "right key";break;
        case vk_lcontrol: string_val_dwk = "l ctrl";break;
        case vk_shift: string_val_dwk = "shift"; break;
        case vk_lalt: string_val_dwk = "l alt";break;
        case vk_tab: string_val_dwk = "tab";break;
        case 20: string_val_dwk = "caps lock";break;
        case 192: string_val_dwk = "`";break;
        case 8:   string_val_dwk = "backspace";break;
        case 189: string_val_dwk = "-";break;
        case 187: string_val_dwk = "=";break;
        case 219: string_val_dwk = "[";break;
        case 221: string_val_dwk = "]";break;
        case 220: string_val_dwk = "|";break;
        case 165: string_val_dwk = "r alt";break;
        case 163: string_val_dwk = "r ctrl";break;
        case 96:  string_val_dwk = "num 0";break;
        case 110: string_val_dwk = "num .";break;
        case 97:  string_val_dwk = "num 1";break;
        case 98:  string_val_dwk = "num 2";break;
        case 99:  string_val_dwk = "num 3";break;
        case 100: string_val_dwk = "num 4";break;
        case 101: string_val_dwk = "num 5";break;
        case 102: string_val_dwk = "num 6";break;
        case 103: string_val_dwk = "num 7";break;
        case 104: string_val_dwk = "num 8";break;
        case 105: string_val_dwk = "num 9";break;
        case 107: string_val_dwk = "num +";break;
        case 144: string_val_dwk = "num lock";break;
        case 111: string_val_dwk = "num /";break;
        case 106: string_val_dwk = "num *";break;
        case 109: string_val_dwk = "num -";break;
        case 145: string_val_dwk = "scroll lock";break;
        case 186: string_val_dwk = ";";break;
        case 222: string_val_dwk = "'";break;
        case 188: string_val_dwk = ",";break;
        case 190: string_val_dwk = ".";break;
        case 191: string_val_dwk = "/";break;
        case 32:  string_val_dwk = "space";break;
        default:  string_val_dwk = chr(dwk);break;
    }
switch(lk)
    {
        case vk_up: string_val_lk = "up key";break;
        case vk_down: string_val_lk = "down key";break;
        case vk_left: string_val_lk = "left key";break;
        case vk_right: string_val_lk = "right key";break;
        case vk_lcontrol: string_val_lk = "l ctrl";break;
        case vk_shift: string_val_lk = "shift"; break;
        case vk_lalt: string_val_lk = "l alt";break;
        case vk_tab: string_val_lk = "tab";break;
        case 20: string_val_lk = "caps lock";break;
        case 192: string_val_lk = "`";break;
        case 8:   string_val_lk = "backspace";break;
        case 189: string_val_lk = "-";break;
        case 187: string_val_lk = "=";break;
        case 219: string_val_lk = "[";break;
        case 221: string_val_lk = "]";break;
        case 220: string_val_lk = "|";break;
        case 165: string_val_lk = "r alt";break;
        case 163: string_val_lk = "r ctrl";break;
        case 96:  string_val_lk = "num 0";break;
        case 110: string_val_lk = "num .";break;
        case 97:  string_val_lk = "num 1";break;
        case 98:  string_val_lk = "num 2";break;
        case 99:  string_val_lk = "num 3";break;
        case 100: string_val_lk = "num 4";break;
        case 101: string_val_lk = "num 5";break;
        case 102: string_val_lk = "num 6";break;
        case 103: string_val_lk = "num 7";break;
        case 104: string_val_lk = "num 8";break;
        case 105: string_val_lk = "num 9";break;
        case 107: string_val_lk = "num +";break;
        case 144: string_val_lk = "num lock";break;
        case 111: string_val_lk = "num /";break;
        case 106: string_val_lk = "num *";break;
        case 109: string_val_lk = "num -";break;
        case 145: string_val_lk = "scroll lock";break;
        case 186: string_val_lk = ";";break;
        case 222: string_val_lk = "'";break;
        case 188: string_val_lk = ",";break;
        case 190: string_val_lk = ".";break;
        case 191: string_val_lk = "/";break;
        case 32:  string_val_lk = "space";break;
        default:  string_val_lk = chr(lk);break;
    }
switch(rk)
    {
        case vk_up: string_val_rk = "up key";break;
        case vk_down: string_val_rk = "down key";break;
        case vk_left: string_val_rk = "left key";break;
        case vk_right: string_val_rk = "right key";break;
        case vk_lcontrol: string_val_rk = "l ctrl";break;
        case vk_shift: string_val_rk = "shift"; break;
        case vk_lalt: string_val_rk = "l alt";break;
        case vk_tab: string_val_rk = "tab";break;
        case 20: string_val_rk = "caps lock";break;
        case 192: string_val_rk = "`";break;
        case 8:   string_val_rk = "backspace";break;
        case 189: string_val_rk = "-";break;
        case 187: string_val_rk = "=";break;
        case 219: string_val_rk = "[";break;
        case 221: string_val_rk = "]";break;
        case 220: string_val_rk = "|";break;
        case 165: string_val_rk = "r alt";break;
        case 163: string_val_rk = "r ctrl";break;
        case 96:  string_val_rk = "num 0";break;
        case 110: string_val_rk = "num .";break;
        case 97:  string_val_rk = "num 1";break;
        case 98:  string_val_rk = "num 2";break;
        case 99:  string_val_rk = "num 3";break;
        case 100: string_val_rk = "num 4";break;
        case 101: string_val_rk = "num 5";break;
        case 102: string_val_rk = "num 6";break;
        case 103: string_val_rk = "num 7";break;
        case 104: string_val_rk = "num 8";break;
        case 105: string_val_rk = "num 9";break;
        case 107: string_val_rk = "num +";break;
        case 144: string_val_rk = "num lock";break;
        case 111: string_val_rk = "num /";break;
        case 106: string_val_rk = "num *";break;
        case 109: string_val_rk = "num -";break;
        case 145: string_val_rk = "scroll lock";break;
        case 186: string_val_rk = ";";break;
        case 222: string_val_rk = "'";break;
        case 188: string_val_rk = ",";break;
        case 190: string_val_rk = ".";break;
        case 191: string_val_rk = "/";break;
        case 32:  string_val_rk = "space";break;
        default:  string_val_rk = chr(rk);break;
    }
switch(jk)
    {
        case vk_up: string_val_jk = "up key";break;
        case vk_down: string_val_jk = "down key";break;
        case vk_left: string_val_jk = "left key";break;
        case vk_right: string_val_jk = "right key";break;
        case vk_lcontrol: string_val_jk = "l ctrl";break;
        case vk_shift: string_val_jk = "shift"; break;
        case vk_lalt: string_val_jk = "l alt";break;
        case vk_tab: string_val_jk = "tab";break;
        case 20: string_val_jk = "caps lock";break;
        case 192: string_val_jk = "`";break;
        case 8:   string_val_jk = "backspace";break;
        case 189: string_val_jk = "-";break;
        case 187: string_val_jk = "=";break;
        case 219: string_val_jk = "[";break;
        case 221: string_val_jk = "]";break;
        case 220: string_val_jk = "|";break;
        case 165: string_val_jk = "r alt";break;
        case 163: string_val_jk = "r ctrl";break;
        case 96:  string_val_jk = "num 0";break;
        case 110: string_val_jk = "num .";break;
        case 97:  string_val_jk = "num 1";break;
        case 98:  string_val_jk = "num 2";break;
        case 99:  string_val_jk = "num 3";break;
        case 100: string_val_jk = "num 4";break;
        case 101: string_val_jk = "num 5";break;
        case 102: string_val_jk = "num 6";break;
        case 103: string_val_jk = "num 7";break;
        case 104: string_val_jk = "num 8";break;
        case 105: string_val_jk = "num 9";break;
        case 107: string_val_jk = "num +";break;
        case 144: string_val_jk = "num lock";break;
        case 111: string_val_jk = "num /";break;
        case 106: string_val_jk = "num *";break;
        case 109: string_val_jk = "num -";break;
        case 145: string_val_jk = "scroll lock";break;
        case 186: string_val_jk = ";";break;
        case 222: string_val_jk = "'";break;
        case 188: string_val_jk = ",";break;
        case 190: string_val_jk = ".";break;
        case 191: string_val_jk = "/";break;
        case 32:  string_val_jk = "space";break;
        default:  string_val_jk = chr(jk);break;
    }
switch(ak)
    {
        case vk_up: string_val_ak = "up key";break;
        case vk_down: string_val_ak = "down key";break;
        case vk_left: string_val_ak = "left key";break;
        case vk_right: string_val_ak = "right key";break;
        case vk_lcontrol: string_val_ak = "l ctrl";break;
        case vk_shift: string_val_ak = "shift"; break;
        case vk_lalt: string_val_ak = "l alt";break;
        case vk_tab: string_val_ak = "tab";break;
        case 20: string_val_ak = "caps lock";break;
        case 192: string_val_ak = "`";break;
        case 8:   string_val_ak = "backspace";break;
        case 189: string_val_ak = "-";break;
        case 187: string_val_ak = "=";break;
        case 219: string_val_ak = "[";break;
        case 221: string_val_ak = "]";break;
        case 220: string_val_ak = "|";break;
        case 165: string_val_ak = "r alt";break;
        case 163: string_val_ak = "r ctrl";break;
        case 96:  string_val_ak = "num 0";break;
        case 110: string_val_ak = "num .";break;
        case 97:  string_val_ak = "num 1";break;
        case 98:  string_val_ak = "num 2";break;
        case 99:  string_val_ak = "num 3";break;
        case 100: string_val_ak = "num 4";break;
        case 101: string_val_ak = "num 5";break;
        case 102: string_val_ak = "num 6";break;
        case 103: string_val_ak = "num 7";break;
        case 104: string_val_ak = "num 8";break;
        case 105: string_val_ak = "num 9";break;
        case 107: string_val_ak = "num +";break;
        case 144: string_val_ak = "num lock";break;
        case 111: string_val_ak = "num /";break;
        case 106: string_val_ak = "num *";break;
        case 109: string_val_ak = "num -";break;
        case 145: string_val_ak = "scroll lock";break;
        case 186: string_val_ak = ";";break;
        case 222: string_val_ak = "'";break;
        case 188: string_val_ak = ",";break;
        case 190: string_val_ak = ".";break;
        case 191: string_val_ak = "/";break;
        case 32:  string_val_ak = "space";break;
        default:  string_val_ak = chr(ak);break;
    }
switch(dk)
    {
        case vk_up: string_val_dk = "up key";break;
        case vk_down: string_val_dk = "down key";break;
        case vk_left: string_val_dk = "left key";break;
        case vk_right: string_val_dk = "right key";break;
        case vk_lcontrol: string_val_dk = "l ctrl";break;
        case vk_shift: string_val_dk = "shift"; break;
        case vk_lalt: string_val_dk = "l alt";break;
        case vk_tab: string_val_dk = "tab";break;
        case 20: string_val_dk = "caps lock";break;
        case 192: string_val_dk = "`";break;
        case 8:   string_val_dk = "backspace";break;
        case 189: string_val_dk = "-";break;
        case 187: string_val_dk = "=";break;
        case 219: string_val_dk = "[";break;
        case 221: string_val_dk = "]";break;
        case 220: string_val_dk = "|";break;
        case 165: string_val_dk = "r alt";break;
        case 163: string_val_dk = "r ctrl";break;
        case 96:  string_val_dk = "num 0";break;
        case 110: string_val_dk = "num .";break;
        case 97:  string_val_dk = "num 1";break;
        case 98:  string_val_dk = "num 2";break;
        case 99:  string_val_dk = "num 3";break;
        case 100: string_val_dk = "num 4";break;
        case 101: string_val_dk = "num 5";break;
        case 102: string_val_dk = "num 6";break;
        case 103: string_val_dk = "num 7";break;
        case 104: string_val_dk = "num 8";break;
        case 105: string_val_dk = "num 9";break;
        case 107: string_val_dk = "num +";break;
        case 144: string_val_dk = "num lock";break;
        case 111: string_val_dk = "num /";break;
        case 106: string_val_dk = "num *";break;
        case 109: string_val_dk = "num -";break;
        case 145: string_val_dk = "scroll lock";break;
        case 186: string_val_dk = ";";break;
        case 222: string_val_dk = "'";break;
        case 188: string_val_dk = ",";break;
        case 190: string_val_dk = ".";break;
        case 191: string_val_dk = "/";break;
        case 32:  string_val_dk = "space";break;
        default:  string_val_dk = chr(dk);break;
    }
switch(ik)
    {
        case vk_up: string_val_ik = "up key";break;
        case vk_down: string_val_ik = "down key";break;
        case vk_left: string_val_ik = "left key";break;
        case vk_right: string_val_ik = "right key";break;
        case vk_lcontrol: string_val_ik = "l ctrl";break;
        case vk_shift: string_val_ik = "shift"; break;
        case vk_lalt: string_val_ik = "l alt";break;
        case vk_tab: string_val_ik = "tab";break;
        case 20: string_val_ik = "caps lock";break;
        case 192: string_val_ik = "`";break;
        case 8:   string_val_ik = "backspace";break;
        case 189: string_val_ik = "-";break;
        case 187: string_val_ik = "=";break;
        case 219: string_val_ik = "[";break;
        case 221: string_val_ik = "]";break;
        case 220: string_val_ik = "|";break;
        case 165: string_val_ik = "r alt";break;
        case 163: string_val_ik = "r ctrl";break;
        case 96:  string_val_ik = "num 0";break;
        case 110: string_val_ik = "num .";break;
        case 97:  string_val_ik = "num 1";break;
        case 98:  string_val_ik = "num 2";break;
        case 99:  string_val_ik = "num 3";break;
        case 100: string_val_ik = "num 4";break;
        case 101: string_val_ik = "num 5";break;
        case 102: string_val_ik = "num 6";break;
        case 103: string_val_ik = "num 7";break;
        case 104: string_val_ik = "num 8";break;
        case 105: string_val_ik = "num 9";break;
        case 107: string_val_ik = "num +";break;
        case 144: string_val_ik = "num lock";break;
        case 111: string_val_ik = "num /";break;
        case 106: string_val_ik = "num *";break;
        case 109: string_val_ik = "num -";break;
        case 145: string_val_ik = "scroll lock";break;
        case 186: string_val_ik = ";";break;
        case 222: string_val_ik = "'";break;
        case 188: string_val_ik = ",";break;
        case 190: string_val_ik = ".";break;
        case 191: string_val_ik = "/";break;
        case 32:  string_val_ik = "space";break;
        default:  string_val_ik = chr(ik);break;
    }

draw_text_color(camera_get_view_x(view_camera[0])+270,camera_get_view_y(view_camera[0])+55,string_val_upk,col,col,col,col,1);
draw_text_color(camera_get_view_x(view_camera[0])+270,camera_get_view_y(view_camera[0])+71,string_val_dwk,col,col,col,col,1);
draw_text_color(camera_get_view_x(view_camera[0])+270,camera_get_view_y(view_camera[0])+87,string_val_lk,col,col,col,col,1);
draw_text_color(camera_get_view_x(view_camera[0])+270,camera_get_view_y(view_camera[0])+103,string_val_rk,col,col,col,col,1);
draw_text_color(camera_get_view_x(view_camera[0])+270,camera_get_view_y(view_camera[0])+119,string_val_jk,col,col,col,col,1);
draw_text_color(camera_get_view_x(view_camera[0])+270,camera_get_view_y(view_camera[0])+135,string_val_ak,col,col,col,col,1);
draw_text_color(camera_get_view_x(view_camera[0])+270,camera_get_view_y(view_camera[0])+151,string_val_dk,col,col,col,col,1);
draw_text_color(camera_get_view_x(view_camera[0])+270,camera_get_view_y(view_camera[0])+167,string_val_ik,col,col,col,col,1);


